### ISSUE TITLE
ti pidor

### ISSUE THREAD

**Issue by thickdev** [daDnl/oap#1]

**Comment by daDnl** [comment]
no u

**Comment by thickdev** [comment]
ok bye

**Comment by thickdev** [comment]
[https://i.pinimg.com/originals/bd/06/22/bd06227e37089779b0a6fc713b9fc27e.jpg](url)

**Comment by thickdev** [comment]
[https://i.pinimg.com/originals/bd/06/22/bd06227e37089779b0a6fc713b9fc27e.jpg](url)

**Comment by thickdev** [comment]
удали кста
